# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_modular_headers!

target 'AwesomeProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native'
  pod 'react-native-nend-sdk', path: '../node_modules/react-native-nend-sdk'
end
